; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
monitor_speed = 115200
monitor_filters = time
framework = arduino
lib_deps = 
    https://github.com/DFRobot/DFRobot_MultiGasSensor.git


[env:ESP32C3LOLIN]
platform = espressif32 @ 6.9.0
board = lolin_c3_mini
monitor_speed = 115200
monitor_filters = time
framework = arduino
lib_deps = 
    https://github.com/DFRobot/DFRobot_MultiGasSensor.git
build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1

[env:XIAOS3]
platform = espressif32 @ 6.9.0
board = seeed_xiao_esp32s3
monitor_speed = 115200
monitor_filters = time
framework = arduino
lib_deps = 
    https://github.com/DFRobot/DFRobot_MultiGasSensor.git
build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1